# Generated by Django 2.2.5 on 2019-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westwood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonform',
            name='evolution_sets',
            field=models.IntegerField(default=0),
        ),
    ]
