# Generated by Django 3.0.7 on 2020-07-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('westwood', '0002_pokemonform_evolution_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=500)),
                ('cost', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TmRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField()),
                ('tm_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westwood.TmDefinition')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='tm_records',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemonform',
            name='evolution_sets',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='TmRecordsListElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('sequence_number', models.IntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westwood.TmRecord')),
            ],
        ),
    ]
